### ISSUE TITLE
Announcement: Transfering repository to @progrhyme

### ISSUE THREAD

**Issue by key-amb** [key-amb/perl5-AWS-CLI-Config#6]
To whom it may concern,

I'm transfering  my repositories to @progrhyme who is my new account.
I already transfered most of my repositories to him.

I don't think this would occur any trouble. GitHub automatically redirects accesses to old URLs to new ones.
But please take care just in case.

If you are unfamiliar with _repository transfers on GitHub_, [this document](https://help.github.com/articles/about-repository-transfers/) will be helpful.

I will execute this transfer in 1 week.

Thanks,

**Comment by progrhyme** [comment]
Completed.
If you find any problem with this change, let me (@progrhyme) know.
